2018-09-07 13:31:52,365 - mysql.py[line:15] - ERROR: (1062, "Duplicate entry 'test' for key 'unique_dirs'")
2018-09-07 13:32:01,588 - mysql.py[line:15] - ERROR: (1318, 'Incorrect number of arguments for PROCEDURE learn.edit_arctype; expected 12, got 13')
2018-09-07 13:34:58,682 - mysql.py[line:15] - ERROR: (1305, 'PROCEDURE learn.edit_arctype does not exist')
2018-09-07 13:35:46,755 - mysql.py[line:15] - ERROR: (1366, 'Incorrect integer value: \'<i class="fa fa-circle-o"></i>\' for column \'sorts\' at row 1')
2018-09-07 13:39:36,495 - mysql.py[line:15] - ERROR: (1062, "Duplicate entry 'test' for key 'unique_dirs'")
2018-09-07 13:41:21,193 - mysql.py[line:15] - ERROR: (1062, "Duplicate entry 'hahhaha' for key 'unique_dirs'")
2018-09-07 13:44:11,860 - mysql.py[line:15] - ERROR: (1062, "Duplicate entry 'c' for key 'unique_dirs'")
2018-09-07 13:47:16,345 - mysql.py[line:15] - ERROR: (1062, "Duplicate entry 'c' for key 'unique_dirs'")
2018-09-07 13:47:17,671 - mysql.py[line:15] - ERROR: (1062, "Duplicate entry 'c' for key 'unique_dirs'")
2018-09-07 13:47:18,550 - mysql.py[line:15] - ERROR: (1062, "Duplicate entry 'c' for key 'unique_dirs'")
2018-09-07 13:47:18,715 - mysql.py[line:15] - ERROR: (1062, "Duplicate entry 'c' for key 'unique_dirs'")
2018-09-07 13:47:18,775 - mysql.py[line:15] - ERROR: (1062, "Duplicate entry 'c' for key 'unique_dirs'")
2018-09-07 13:49:15,022 - mysql.py[line:15] - ERROR: (1062, "Duplicate entry 'c' for key 'unique_dirs'")
2018-09-07 13:51:07,216 - mysql.py[line:15] - ERROR: (1062, "Duplicate entry 'c' for key 'unique_dirs'")
2018-09-07 19:14:02,411 - mysql.py[line:15] - ERROR: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY a.sorts' at line 1")
2018-09-07 20:15:03,910 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:15:05,266 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:15:06,987 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:15:23,385 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:15:28,320 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:15:30,036 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:15:30,720 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:15:32,574 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:15:33,310 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:15:34,094 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:15:34,937 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:15:35,846 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:15:38,440 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:15:43,469 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:16:14,498 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
2018-09-07 20:16:30,353 - mysql.py[line:15] - ERROR: (1054, "Unknown column 'a.mid' in 'field list'")
